Error messages
WeszeRita/reactive-form-registration pull request #2
Opened 2024-01-16 10:27 UTC by WeszeRita

2024-01-16 11:35 UTC, KriszNyikos commented on reactive-form-registration/src/shared/utils/checkForErrorsIn.util.ts
> +export function checkForErrorsIn(formControl: string): string {
Az elnevezés nem megfelelő
Ha a function egy error message-et ad vissza, arra utalj inkább a nevében, hiszen a valódi ok, hogy létrehoztad az, hogy egy üzenetet adjon vissza, pl getErrorMessage.

2024-01-16 11:35 UTC, KriszNyikos commented on reactive-form-registration/src/shared/utils/checkForErrorsIn.util.ts
> +  }
Módosítsuk a util-t a cikk alapján.

```
checkForErrorsIn(formControl:` AbstractControl): string {
  if (formControl.hasError('required')) {
    return 'Min value is required'
  }

  if (formControl.hasError('min') || formControl.hasError('max')) {
    return 'Value must be between 1980 and 2020';
  }
  return ''
}
```
Az egész controlt is átadhatod, így nem kell megint a get method-ot használnod.

2024-01-16 11:35 UTC, KriszNyikos commented on reactive-form-registration/src/app/app.component.ts
> +  checkForErrorMessages = checkForErrorsIn;
ne használj más nevet mint amit importáltál

2024-01-16 11:35 UTC, KriszNyikos commented on reactive-form-registration/src/shared/enums/errorMessage.enum.ts
> +}
fájl nevénél ne használjunk camelCase-t.

Itt lehet default export is, és így közvetlen tudod importálni a nevét, nem kell *

2024-01-16 11:35 UTC, KriszNyikos commented on reactive-form-registration/src/shared/enums/index.ts
MIvel kicsit a feladat, ezért ide nem indokolt az index fájl, de jó ötlet volt.

2024-01-16 11:54 UTC, WeszeRita commented on reactive-form-registration/src/shared/utils/checkForErrorsIn.util.ts
> +export function checkForErrorsIn(formControl: string): string {
done

2024-01-16 13:22 UTC, WeszeRita commented on reactive-form-registration/src/app/app.component.ts
> +  checkForErrorMessages = checkForErrorsIn;
ok

2024-01-16 13:42 UTC, WeszeRita commented on reactive-form-registration/src/shared/enums/errorMessage.enum.ts
> +}
a camelCase-t és a  *-ot kiszedtem, a  default export nem működik, hiába írom át az importot is

2024-01-16 16:35 UTC, WeszeRita commented on reactive-form-registration/src/shared/utils/checkForErrorsIn.util.ts
> +  }
yep

2024-01-17 09:46 UTC, KriszNyikos commented on reactive-form-registration/src/app/app.component.html
> +
Extra line

2024-01-17 09:46 UTC, KriszNyikos commented on reactive-form-registration/src/app/app.component.ts
> +
extra line

2024-01-17 09:46 UTC, KriszNyikos commented on reactive-form-registration/src/app/app.component.ts
>    private readonly phoneRegEx = '^[1-9][0-9]{8}$';
Amennyiben regEx-nek nevezed el, akkor vagy itt tedd regEx constructorba, vagy használj template-et. Itt a következő template-et használhatod /^[1-9][0-9]{8}$/  Igy már csak ezt kell átadnod a validátornak. Kérlek módosítsd át a másikat is, és a validátornál a regExp()-et töröld.

2024-01-17 09:46 UTC, KriszNyikos commented on reactive-form-registration/src/app/app.component.ts
> +        phoneNumber: [null, this.customPatternValidator(RegExp(this.phoneRegEx), 'invalid-phone')],
Ha módosítottad a regEx-et akkor innent a constructort töröld.

2024-01-17 09:46 UTC, KriszNyikos commented on reactive-form-registration/src/app/app.component.ts
> +      return valid ? null : message;
Egy kis Typescript varázslat: a fenti message nevű változó helyett ezt is átadhatod: return valid ? null : {[errorMessage]: true} as ValidationErrors; Így több sort spórolsz

2024-01-17 09:46 UTC, KriszNyikos commented on reactive-form-registration/src/shared/utils/get-error-message.util.ts
> +  if (formControl.hasError('passwordMismatchError')) {
camelCase, az error szócska már nem is kell

2024-01-17 09:46 UTC, KriszNyikos commented on reactive-form-registration/src/shared/enums/errorMessage.enum.ts
> +}
Én arra gondoltam, hogy kihagyhatjuk az indexet, akkor közvetlenül lehet importálni az app.componentbe így
```import getErrorMessage  from 'src/shared/utils/get-error-message.util'```
Működik, teszteltem.
Ne módosítsd erre, a lényeg működik.

2024-01-17 10:02 UTC, WeszeRita commented on reactive-form-registration/src/app/app.component.html
> +
removed

2024-01-17 10:04 UTC, WeszeRita commented on reactive-form-registration/src/app/app.component.ts
> +
csak az angularos importokat és a saját importjaimat válsztottam el

2024-01-17 10:15 UTC, WeszeRita commented on reactive-form-registration/src/app/app.component.ts
> +      return valid ? null : message;
done

2024-01-17 10:21 UTC, KriszNyikos commented on reactive-form-registration/src/app/app.component.ts
> +
Itt felesleges, töröld

2024-01-17 10:49 UTC, WeszeRita commented on reactive-form-registration/src/shared/utils/get-error-message.util.ts
> +  if (formControl.hasError('passwordMismatchError')) {
az error-t kitöröltem, nem tudom mit változtassak camelCase-re

2024-01-20 20:54 UTC, KriszNyikos commented on reactive-form-registration/src/shared/utils/get-error-message.util.ts
> +  if (formControl.hasError('passwordMismatchError')) {
Arra gondoltam, hogy cseréld ki erre :) password-mismatch

2024-01-20 21:29 UTC, KriszNyikos requested changes

2024-01-20 21:29 UTC, KriszNyikos commented on reactive-form-registration/src/shared/utils/get-error-message.util.ts
> +
Sok extra line

2024-01-23 08:33 UTC, merged